[build-system]
requires = [
  "setuptools>=45.0",
  "wheel>=0.36",
]
build-backend = "setuptools.build_meta"

[project]
name = "sv_rom_simulation"
version = "0.1.1"
readme = "README.md"
license = "MIT"
dependencies = [
    "numpy>=2.5",
    "vtk>=9.2",
    "scipy>=1.18",
    "vmtk>=1.5.2",
]

[project.scripts]
sv_rom_simulation-create-solver-file="sv_rom_simulation.generate_1d_mesh:run_cli"

